### ISSUE TITLE
Performance regression introduced by commit "check events on begin of any call"

### ISSUE THREAD

**Issue by cvubrugier** [gphoto/gphotofs#2]
I am having a look at gphotofs performance / memory consumption when downloading large images and I noticed a big performance regression with the latest git revision compared to version 0.5.

The size of the downloaded image is 155 MB. The time, measured with `time`, to download the image is:

- **5 seconds** with gphotofs version 0.5
- more than **6 minutes** with gphotofs latest git revision

I ran `git bisect` and it reported that the first bad commit is revision 8abf537 "check events on begin of any call, so capture new or removed files":

    $ git bisect good
    8abf537223230e31e3e9058ce7ebee42602191f0 is the first bad commit
    commit 8abf537223230e31e3e9058ce7ebee42602191f0
    Author: Marcus Meissner <marcus@jet.franken.de>
    Date:   Sun Nov 1 17:38:53 2015 +0100

        check events on begin of any call, so
        capture new or removed files

    :100644 100644 708d02f72e377e87042f85cacaed345dbb3b2ed8 0eee6cf8064ef5e5b2e5679799ba2528b0d5087c M      gphotofs.c

Additional information:

- I am running Debian testing with the fuse (version 2.9.7) and gphoto2 (version 2.5.10) packages coming from Debian.
- The image is downloaded from a Nexus 5X phone running Android 7.0.

Please tell me if you need further information.

**Comment by msmeissn** [comment]
hmm. we might be callingthis quite often on some setups, so perhaps some form of rate limiting would be good

**Comment by msmeissn** [comment]
i removed it from the read() function now. the rest still have it.

can you retest current git

**Comment by cvubrugier** [comment]
> can you retest current git

I tested the master branch at commit 3c65d3f "updated, prepare for 1.0 release" and the performance regression in read() is fixed.

Thanks Marcus :+1:
